# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10d39cfe77024131784f229ce6fc7d0928e2761fe37e2f0942051def8996d4a84c73b6eef02a55494d614efe972a920306f675614091c770081fc28a35860eb5

test:
  secret_key_base: 4ab4dfa7b3f616308006ba9d0111d9191b315ff11b6d56140b005c7b1ff04570acff8227de368481d079665f9f3e4f069ff216c9303ff97bbef3cd17c96b6c2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
